[package]
name = "scanner-app"
version = "0.1.0"
description = "Native host for Scanner"
authors = ["xtreemze"]
edition = "2024"
rust-version = "1.99.0"

[lib]
name = "scanner_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.0", features = [] }

[dependencies]
scanner-core = { path = "../crates/scanner-core" }
tauri-plugin-scanner-sensors = { path = "../plugins/scanner-sensors" }
serde = { version = "1.0.228", features = ["derive"] }
tauri = { version = "2.12.0", features = [] }
